### ISSUE TITLE
Unexpected value returned by Toyota

### ISSUE THREAD

**Issue by MaximeNagel** [DurgNomis-drol/mytoyota#284]
Testing the new api endpoint for the ha toyota integration

It happend after the setup flow is finished and the integration try to create entitites

**Expected behavior**
I should be able to see my vehicle sensors

**Additional context**
Car is a Toyota Corolla Touring 2021 Hyrbrid

```2024-01-09 08:41:14.233 ERROR (MainThread) [custom_components.toyota] Unexpected error fetching toyota data: 2 validation errors for VehiclesResponseModel
payload -> 0 -> dcm
  none is not an allowed value (type=type_error.none.not_allowed)
payload -> 0 -> electricalPlatformCode
  none is not an allowed value (type=type_error.none.not_allowed)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 256, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/toyota/__init__.py", line 72, in async_get_vehicle_data
    vehicles = await asyncio.wait_for(client.get_vehicles(metric=use_metric_values), 15)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mytoyota/client.py", line 63, in get_vehicles
    vehicles = await self._api.get_vehicles_endpoint()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mytoyota/api.py", line 75, in get_vehicles_endpoint
    return await self._request_and_parse(VehiclesResponseModel, "GET", VEHICLE_GUID_ENDPOINT)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mytoyota/api.py", line 49, in _request_and_parse
    return model(**response)
           ^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for VehiclesResponseModel
payload -> 0 -> dcm
  none is not an allowed value (type=type_error.none.not_allowed)
payload -> 0 -> electricalPlatformCode
  none is not an allowed value (type=type_error.none.not_allowed)```

**Comment by i82hisaj** [comment]
Hello there,

I'm also experiencing this exact issue. In my case, my car is a petrol Toyota Aygo from 2021.

Thanks in advance!

**Comment by MaximeNagel** [comment]
Hi Again @CM000n,

I've tried to test this fix by totally removing ha toyota integration from HA, and manually adding the toyota repo from ha toyota again and restarting HA , but same error happened again.

If I'm not mistaken this is a dependency for ha toyota so I don't need to manually make update to reflect this change ?
By reloading the ha intregation it should update dependency right ? 

Thx for your help

**Comment by CM000n** [comment]
> Hi Again @CM000n,
> 
> I've tried to test this fix by totally removing ha toyota integration from HA, and manually adding the toyota repo from ha toyota again and restarting HA , but same error happened again.
> 
> If I'm not mistaken this is a dependency for ha toyota so I don't need to manually make update to reflect this change ? By reloading the ha intregation it should update dependency right ?
> 
> Thx for your help

The fix has been merged, but there is no new release of the mytoyota lib with it yet 😉

**Comment by MaximeNagel** [comment]
Indeed, as the release version is specified in the manifest.json of ha toyota I need to wait the change to be released and update manifest accordingly. It's not directly linked to the branch main/master.

Sorry to waste your time with such nooby question. I'm also a developer myself, but I have low knowledge in python and this kind of "packaging"

**Comment by CM000n** [comment]
np 👍🏻

**Comment by i82hisaj** [comment]
Hello, I'm still experiencing some issues after the update from yesterday, in this case related to TripsResponseModel:

Please find below the error shown:

`Traceback (most recent call last):
  File "/home/jhidalgo/simple_client_example.py", line 73, in <module>
    loop.run_until_complete(get_information())
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/jhidalgo/simple_client_example.py", line 49, in get_information
    await car.update()
  File "/home/jhidalgo/mytoyota/lib/python3.11/site-packages/mytoyota/models/vehicle.py", line 113, in update
    for name, data in await responses:
                      ^^^^^^^^^^^^^^^
  File "/home/jhidalgo/mytoyota/lib/python3.11/site-packages/mytoyota/models/vehicle.py", line 107, in parallel_wrapper
    r = await function()
        ^^^^^^^^^^^^^^^^
  File "/home/jhidalgo/mytoyota/lib/python3.11/site-packages/mytoyota/api.py", line 220, in get_trips_endpoint
    return await self._request_and_parse(TripsResponseModel, "GET", endpoint, vin=vin)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/jhidalgo/mytoyota/lib/python3.11/site-packages/mytoyota/api.py", line 49, in _request_and_parse
    return model(**response)
           ^^^^^^^^^^^^^^^^^
  File "/home/jhidalgo/mytoyota/lib/python3.11/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 3 validation errors for TripsResponseModel
payload -> trips -> 0 -> scores
  field required (type=value_error.missing)
payload -> trips -> 1 -> scores
  field required (type=value_error.missing)
payload -> summary -> 0 -> scores
  field required (type=value_error.missing)`

Thanks in advance!
